//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioIUC.Localize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BiblioIUC.Localize.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A propos de {0}.
        /// </summary>
        public static string About_x {
            get {
                return ResourceManager.GetString("About_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compte.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compte ou mot de passe incorrect !.
        /// </summary>
        public static string Account_or_password_is_incorrect {
            get {
                return ResourceManager.GetString("Account_or_password_is_incorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activé.
        /// </summary>
        public static string Actived {
            get {
                return ResourceManager.GetString("Actived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue. Réessayez plus tard svp !.
        /// </summary>
        public static string An_error_occured {
            get {
                return ResourceManager.GetString("An_error_occured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avr.
        /// </summary>
        public static string Apr {
            get {
                return ResourceManager.GetString("Apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aou.
        /// </summary>
        public static string Aug {
            get {
                return ResourceManager.GetString("Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auteurs.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Librairie.
        /// </summary>
        public static string Bookstore {
            get {
                return ResourceManager.GetString("Bookstore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcourir....
        /// </summary>
        public static string Browser {
            get {
                return ResourceManager.GetString("Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description de la catégorie.
        /// </summary>
        public static string Category_description {
            get {
                return ResourceManager.GetString("Category_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intitulé de la catégorie.
        /// </summary>
        public static string Category_name {
            get {
                return ResourceManager.GetString("Category_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune catégorie trouvée !.
        /// </summary>
        public static string Category_not_found {
            get {
                return ResourceManager.GetString("Category_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisir une catégorie.
        /// </summary>
        public static string Choose_a_category {
            get {
                return ResourceManager.GetString("Choose_a_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code / ISBN.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributeurs.
        /// </summary>
        public static string Contributors {
            get {
                return ResourceManager.GetString("Contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image de couverture.
        /// </summary>
        public static string Cover_image {
            get {
                return ResourceManager.GetString("Cover_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer une catégorie.
        /// </summary>
        public static string Create_a_category {
            get {
                return ResourceManager.GetString("Create_a_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un document.
        /// </summary>
        public static string Create_a_document {
            get {
                return ResourceManager.GetString("Create_a_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un utilisateur.
        /// </summary>
        public static string Create_a_user {
            get {
                return ResourceManager.GetString("Create_a_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critique.
        /// </summary>
        public static string Danger {
            get {
                return ResourceManager.GetString("Danger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableau de bord.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donnée inexistante ou supprimée !.
        /// </summary>
        public static string Data_not_exists_or_deleted {
            get {
                return ResourceManager.GetString("Data_not_exists_or_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        public static string Dec {
            get {
                return ResourceManager.GetString("Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression réussie !.
        /// </summary>
        public static string Delete_done {
            get {
                return ResourceManager.GetString("Delete_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer ce fichier à l&apos;enregistrement.
        /// </summary>
        public static string Delete_this_file_on_save {
            get {
                return ResourceManager.GetString("Delete_this_file_on_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer cette image à l&apos;enregistrement.
        /// </summary>
        public static string Delete_this_image_on_save {
            get {
                return ResourceManager.GetString("Delete_this_image_on_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimé.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description/Résumé.
        /// </summary>
        public static string Description_Resume {
            get {
                return ResourceManager.GetString("Description_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désactivé.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous vraiment supprimer {0} ?.
        /// </summary>
        public static string Do_you_really_want_to_delete_x {
            get {
                return ResourceManager.GetString("Do_you_really_want_to_delete_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string Document {
            get {
                return ResourceManager.GetString("Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auteur du document.
        /// </summary>
        public static string Document_author {
            get {
                return ResourceManager.GetString("Document_author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégories de document.
        /// </summary>
        public static string Document_categories {
            get {
                return ResourceManager.GetString("Document_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code ou ISBN du document.
        /// </summary>
        public static string Document_code_or_isbn {
            get {
                return ResourceManager.GetString("Document_code_or_isbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributeurs du document.
        /// </summary>
        public static string Document_contributors {
            get {
                return ResourceManager.GetString("Document_contributors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description ou resumé du document.
        /// </summary>
        public static string Document_description {
            get {
                return ResourceManager.GetString("Document_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents dans la même catégorie.
        /// </summary>
        public static string Document_in_same_category {
            get {
                return ResourceManager.GetString("Document_in_same_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue du document.
        /// </summary>
        public static string Document_language {
            get {
                return ResourceManager.GetString("Document_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun document trouvé !.
        /// </summary>
        public static string Document_not_found {
            get {
                return ResourceManager.GetString("Document_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de pages du document.
        /// </summary>
        public static string Document_number_of_pages {
            get {
                return ResourceManager.GetString("Document_number_of_pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de publication du document.
        /// </summary>
        public static string Document_publish_date {
            get {
                return ResourceManager.GetString("Document_publish_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editeur du document.
        /// </summary>
        public static string Document_publisher {
            get {
                return ResourceManager.GetString("Document_publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous-titre du document.
        /// </summary>
        public static string Document_subtitle {
            get {
                return ResourceManager.GetString("Document_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre du document.
        /// </summary>
        public static string Document_title {
            get {
                return ResourceManager.GetString("Document_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents: {0}.
        /// </summary>
        public static string Documents_x {
            get {
                return ResourceManager.GetString("Documents_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier une catégorie.
        /// </summary>
        public static string Edit_a_category {
            get {
                return ResourceManager.GetString("Edit_a_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer un document.
        /// </summary>
        public static string Edit_a_document {
            get {
                return ResourceManager.GetString("Edit_a_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer un utilisateur.
        /// </summary>
        public static string Edit_a_user {
            get {
                return ResourceManager.GetString("Edit_a_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer votre profil.
        /// </summary>
        public static string Edit_your_profile {
            get {
                return ResourceManager.GetString("Edit_your_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activé.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminé.
        /// </summary>
        public static string Ended {
            get {
                return ResourceManager.GetString("Ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraire les métadonnées.
        /// </summary>
        public static string Extract_metadata {
            get {
                return ResourceManager.GetString("Extract_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fev.
        /// </summary>
        public static string Feb {
            get {
                return ResourceManager.GetString("Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe oublé ?.
        /// </summary>
        public static string Forgotten_password {
            get {
                return ResourceManager.GetString("Forgotten_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom complet.
        /// </summary>
        public static string Full_name {
            get {
                return ResourceManager.GetString("Full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Générer.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment lire un document ?.
        /// </summary>
        public static string How_to_read_a_document {
            get {
                return ResourceManager.GetString("How_to_read_a_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image illustrative.
        /// </summary>
        public static string Illustrative_image {
            get {
                return ResourceManager.GetString("Illustrative_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En cours.
        /// </summary>
        public static string InProcess {
            get {
                return ResourceManager.GetString("InProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string ISBN {
            get {
                return ResourceManager.GetString("ISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        public static string Jan {
            get {
                return ResourceManager.GetString("Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jui.
        /// </summary>
        public static string Jul {
            get {
                return ResourceManager.GetString("Jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        public static string Jun {
            get {
                return ResourceManager.GetString("Jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intitulé.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savoir+.
        /// </summary>
        public static string Learn_more {
            get {
                return ResourceManager.GetString("Learn_more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chargement....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connexion.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déconnexion.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        public static string Mar {
            get {
                return ResourceManager.GetString("Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mai.
        /// </summary>
        public static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun parent.
        /// </summary>
        public static string No_parent {
            get {
                return ResourceManager.GetString("No_parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        public static string Nov {
            get {
                return ResourceManager.GetString("Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de pages.
        /// </summary>
        public static string Number_of_pages {
            get {
                return ResourceManager.GetString("Number_of_pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        public static string Oct {
            get {
                return ResourceManager.GetString("Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagination.
        /// </summary>
        public static string Paging {
            get {
                return ResourceManager.GetString("Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie parent.
        /// </summary>
        public static string Parent_category {
            get {
                return ResourceManager.GetString("Parent_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mot de passe.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo de profil.
        /// </summary>
        public static string Photo_profile {
            get {
                return ResourceManager.GetString("Photo_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de publication.
        /// </summary>
        public static string Publish_date {
            get {
                return ResourceManager.GetString("Publish_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editeur.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lire.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lire un livre.
        /// </summary>
        public static string Read_a_book {
            get {
                return ResourceManager.GetString("Read_a_book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lecture.
        /// </summary>
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lectures.
        /// </summary>
        public static string Readings {
            get {
                return ResourceManager.GetString("Readings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperçu des lectures.
        /// </summary>
        public static string Readings_overview {
            get {
                return ResourceManager.GetString("Readings_overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répéter le mot de passe.
        /// </summary>
        public static string Repeat_password {
            get {
                return ResourceManager.GetString("Repeat_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Répéter votre mot de passe.
        /// </summary>
        public static string Repeat_your_password {
            get {
                return ResourceManager.GetString("Repeat_your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to information requise..
        /// </summary>
        public static string Required_fields {
            get {
                return ResourceManager.GetString("Required_fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrer &amp; mettre à jour les métadonnées du document.
        /// </summary>
        public static string Save_and_update_metadata_file {
            get {
                return ResourceManager.GetString("Save_and_update_metadata_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement réussi !.
        /// </summary>
        public static string Save_done {
            get {
                return ResourceManager.GetString("Save_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enregistrement éffectué ! Mais sans modification des métadonnées..
        /// </summary>
        public static string Save_done_but_without_update_metadata {
            get {
                return ResourceManager.GetString("Save_done_but_without_update_metadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Défilement.
        /// </summary>
        public static string Scroll {
            get {
                return ResourceManager.GetString("Scroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résultat de la recherche de catégorie : {0}.
        /// </summary>
        public static string Search_category_results_of_x {
            get {
                return ResourceManager.GetString("Search_category_results_of_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résultat de la recherche du document: {0}.
        /// </summary>
        public static string Search_document_results_of_x {
            get {
                return ResourceManager.GetString("Search_document_results_of_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résultat de la recherche de l&apos;utilisateur {0}.
        /// </summary>
        public static string Search_user_results_of_x {
            get {
                return ResourceManager.GetString("Search_user_results_of_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher une catégorie....
        /// </summary>
        public static string Searh_a_category {
            get {
                return ResourceManager.GetString("Searh_a_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher un document....
        /// </summary>
        public static string Searh_a_document {
            get {
                return ResourceManager.GetString("Searh_a_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher un utilisateur....
        /// </summary>
        public static string Searh_a_user {
            get {
                return ResourceManager.GetString("Searh_a_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep.
        /// </summary>
        public static string Sep {
            get {
                return ResourceManager.GetString("Sep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partager.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentification.
        /// </summary>
        public static string Sign_in {
            get {
                return ResourceManager.GetString("Sign_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statut.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous catégories.
        /// </summary>
        public static string Sub_categories {
            get {
                return ResourceManager.GetString("Sub_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous catégorie.
        /// </summary>
        public static string Sub_category {
            get {
                return ResourceManager.GetString("Sub_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous-titre.
        /// </summary>
        public static string Sub_title {
            get {
                return ResourceManager.GetString("Sub_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion.
        /// </summary>
        public static string Suggestion {
            get {
                return ResourceManager.GetString("Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changer de vue.
        /// </summary>
        public static string Switch_view {
            get {
                return ResourceManager.GetString("Switch_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le document.
        /// </summary>
        public static string The_document {
            get {
                return ResourceManager.GetString("The_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les documents.
        /// </summary>
        public static string The_documents {
            get {
                return ResourceManager.GetString("The_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champs {0} doit avoir au moins {1} caractères !.
        /// </summary>
        public static string The_field_x_must_have_at_least_y_characters {
            get {
                return ResourceManager.GetString("The_field_x_must_have_at_least_y_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champs {0} doit avoir au plus {1} caractères !.
        /// </summary>
        public static string The_field_x_must_have_most_y_characters {
            get {
                return ResourceManager.GetString("The_field_x_must_have_most_y_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ {0}  est requis !.
        /// </summary>
        public static string The_fields_x_is_required {
            get {
                return ResourceManager.GetString("The_fields_x_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les utilisateurs.
        /// </summary>
        public static string The_users {
            get {
                return ResourceManager.GetString("The_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce compte a été désactivé !.
        /// </summary>
        public static string This_account_has_been_disabled {
            get {
                return ResourceManager.GetString("This_account_has_been_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top {0} des lectures par catégorie.
        /// </summary>
        public static string Top_x_of_readings_by_category {
            get {
                return ResourceManager.GetString("Top_x_of_readings_by_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top {0} des lectures par sous-catégorie.
        /// </summary>
        public static string Top_x_of_readings_by_sub_category {
            get {
                return ResourceManager.GetString("Top_x_of_readings_by_sub_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charger le document.
        /// </summary>
        public static string Upload_the_document {
            get {
                return ResourceManager.GetString("Upload_the_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun utilisateur trouvé !.
        /// </summary>
        public static string User_not_found {
            get {
                return ResourceManager.GetString("User_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilisateurs.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir les documents.
        /// </summary>
        public static string View_documents {
            get {
                return ResourceManager.GetString("View_documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voir les sous-catégories.
        /// </summary>
        public static string View_sub_categories {
            get {
                return ResourceManager.GetString("View_sub_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} existe déjà !.
        /// </summary>
        public static string x_already_existant {
            get {
                return ResourceManager.GetString("x_already_existant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} and {0} doesn&apos;t matches !.
        /// </summary>
        public static string x_and_y_doesn_t_matches {
            get {
                return ResourceManager.GetString("x_and_y_doesn_t_matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} min est {1} !.
        /// </summary>
        public static string x_minimum_value_is_y {
            get {
                return ResourceManager.GetString("x_minimum_value_is_y", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous catégories de : {0}.
        /// </summary>
        public static string x_sub_categories {
            get {
                return ResourceManager.GetString("x_sub_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre compte.
        /// </summary>
        public static string Your_account {
            get {
                return ResourceManager.GetString("Your_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre compte a été désactivé !.
        /// </summary>
        public static string Your_account_has_been_disabled {
            get {
                return ResourceManager.GetString("Your_account_has_been_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre compte n&apos;est pas encore activé !.
        /// </summary>
        public static string Your_account_has_been_not_yet_actived {
            get {
                return ResourceManager.GetString("Your_account_has_been_not_yet_actived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre nom complet.
        /// </summary>
        public static string Your_full_name {
            get {
                return ResourceManager.GetString("Your_full_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre mot de passe.
        /// </summary>
        public static string Your_password {
            get {
                return ResourceManager.GetString("Your_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre photo de profil.
        /// </summary>
        public static string Your_photo_profile {
            get {
                return ResourceManager.GetString("Your_photo_profile", resourceCulture);
            }
        }
    }
}
